/** OpenClaw 集成: skill + MCP(官方 CLI) + before_prompt_build 桥接插件。
 *
 *  模式借自 ai-memory 的 OpenClaw 支持(生成 TS 插件 + `openclaw plugins install --link`),
 *  但 exomind 只需要 prompt 上下文注入——不重写逻辑,桥接现有 `emcli hook` 的
 *  stdin({prompt})/stdout(additionalContext) 契约,三宿主共享同一份实现
 *  (关键词注入/暗号/每日发现/origin-marker 去重全部复用)。
 *
 *  三通道:
 *  - skill  → ~/.openclaw/skills/exomind/SKILL.md(扁平 frontmatter,复用 claude 版)
 *  - hook   → ~/.exomind/openclaw-plugin/ 生成包,plugins install --link + gateway restart
 *  - MCP    → `openclaw mcp add exomind --command <emcli绝对路径> --arg mcp`(官方 CLI,自带 probe)
 */
import * as fs from 'node:fs';
import * as path from 'node:path';
import * as os from 'node:os';
import { spawn } from 'node:child_process';
import { CLAUDE_SKILL_SRC } from './install';

export const OPENCLAW_PLUGIN_DIR_NAME = 'openclaw-plugin';

/** 解析 OpenClaw home: OPENCLAW_HOME env 优先,否则 ~/.openclaw。 */
export function resolveOpenclawHome(env = process.env, homeDir = os.homedir()): string {
  const configured = (env.OPENCLAW_HOME ?? '').trim();
  return configured ? path.resolve(configured) : path.join(homeDir, '.openclaw');
}

/** 当前 emcli 可执行入口的绝对路径(烧进生成的插件与 MCP 配置——
 *  OpenClaw gateway 常以 LaunchAgent 跑,PATH 里未必有 npm global bin)。 */
export function emcliEntryPath(): string {
  return path.resolve(process.argv[1] ?? 'emcli');
}

/** 装 OpenClaw skill: 拷 SKILL.md → <openclawHome>/skills/exomind/SKILL.md。
 *  原子写(tmp+rename)+ 备份 + 幂等(覆盖)。skill 源复用 claude 版
 *  (OpenClaw 兼容 Anthropic 扁平 frontmatter:name/description)。 */
export function installOpenclawSkill(
  openclawHome: string,
  skillSrc = CLAUDE_SKILL_SRC,
): { ok: boolean; dest: string; reason?: string } {
  const destDir = path.join(openclawHome, 'skills', 'exomind');
  const dest = path.join(destDir, 'SKILL.md');
  if (!fs.existsSync(skillSrc)) {
    return { ok: false, dest, reason: `skill 源不存在: ${skillSrc}` };
  }
  fs.mkdirSync(destDir, { recursive: true });
  const tmp = `${dest}.tmp-${process.pid}-${Date.now()}`;
  fs.writeFileSync(tmp, fs.readFileSync(skillSrc));
  fs.renameSync(tmp, dest);
  return { ok: true, dest };
}

/** 生成 OpenClaw 插件三件套内容(package.json / openclaw.plugin.json / index.ts)。 */
export function openclawPluginFiles(emcliPath: string, version: string): Record<string, string> {
  const pkgJson = {
    name: '@exomind/openclaw-plugin',
    version,
    private: true,
    type: 'module',
    openclaw: { extensions: ['./index.ts'] },
  };
  const manifest = {
    id: 'exomind',
    name: 'exomind',
    description: 'Inject ExoMind knowledge-flywheel context into prompts (bridges emcli hook).',
    activation: { onCapabilities: ['hook'] },
    configSchema: { type: 'object', additionalProperties: false, properties: {} },
  };
  const entry = `// Generated by \`emcli install\` — do not edit; regenerate with \`emcli install\`.
// Bridges OpenClaw's before_prompt_build to the shared \`emcli hook\` stdin/stdout
// contract, so keyword context, archive keywords, daily discovery, and origin-marker
// dedup all reuse the same implementation as the Claude Code hook.
import { spawn } from 'node:child_process';

const EMCLI = ${JSON.stringify(emcliPath)};
const DEADLINE_MS = 3500; // emcli hook 自身 3s 硬 deadline(R10),留 0.5s spawn 余量

function promptText(value: unknown): string {
  if (value === null || value === undefined) return '';
  if (typeof value === 'string') return value;
  if (Array.isArray(value)) return value.map(promptText).filter(Boolean).join('\\n\\n').trim();
  const obj = value as { prompt?: unknown; userPrompt?: unknown; message?: unknown; text?: unknown };
  for (const v of [obj.prompt, obj.userPrompt, obj.message, obj.text]) {
    const s = promptText(v);
    if (s) return s;
  }
  return '';
}

function runHook(prompt: string): Promise<string> {
  return new Promise((resolve) => {
    let child: ReturnType<typeof spawn>;
    try {
      child = spawn(EMCLI, ['hook'], { stdio: ['pipe', 'pipe', 'ignore'] });
    } catch {
      resolve('');
      return;
    }
    let out = '';
    let settled = false;
    const finish = (v: string): void => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      try {
        child.kill();
      } catch {
        /* ignore */
      }
      resolve(v.trim());
    };
    const timer = setTimeout(() => finish(''), DEADLINE_MS);
    child.stdout?.on('data', (d: Buffer) => {
      out += d.toString();
    });
    child.on('error', () => finish(''));
    child.on('close', () => finish(out));
    try {
      child.stdin?.write(JSON.stringify({ prompt }));
      child.stdin?.end();
    } catch {
      finish('');
    }
  });
}

// SessionEnd 采集探针(P3 会话编译前置):fire-and-forget,喂会话元数据给
// emcli hook-session-end 落本地事件流。失败静默——会话结束路径不容阻塞。
function fireSessionEnd(event: any, ctx: any): void {
  let child: ReturnType<typeof spawn>;
  try {
    child = spawn(EMCLI, ['hook-session-end'], { stdio: ['pipe', 'ignore', 'ignore'] });
  } catch {
    return;
  }
  const timer = setTimeout(() => {
    try {
      child.kill();
    } catch {
      /* ignore */
    }
  }, DEADLINE_MS);
  timer.unref?.();
  child.on('error', () => clearTimeout(timer));
  child.on('close', () => clearTimeout(timer));
  try {
    child.stdin?.write(
      JSON.stringify({
        source: 'openclaw',
        session_id: ctx?.sessionId ?? ctx?.sessionID ?? event?.sessionId ?? event?.sessionID,
        cwd: ctx?.workspaceDir ?? ctx?.cwd ?? event?.cwd,
        reason: event?.reason,
      }),
    );
    child.stdin?.end();
  } catch {
    /* ignore */
  }
}

export function register(api: any): void {
  // register 必须同步(OpenClaw 加载器要求),异步桥接放在事件 handler 里
  api.on('before_prompt_build', async (event: any, _ctx: any) => {
    const prompt = promptText(
      event?.prompt ?? event?.userPrompt ?? event?.message ?? event?.messages?.at?.(-1),
    );
    if (!prompt) return undefined;
    const out = await runHook(prompt);
    return out ? { prependContext: out } : undefined;
  });
  api.on('session_end', (event: any, ctx: any) => {
    fireSessionEnd(event, ctx);
  });
}
`;
  return {
    'package.json': JSON.stringify(pkgJson, null, 2) + '\n',
    'openclaw.plugin.json': JSON.stringify(manifest, null, 2) + '\n',
    'index.ts': entry,
  };
}

/** 写插件包到 <exomindConfigDir>/openclaw-plugin/(覆盖式,生成物无需备份)。返回写入路径列表。 */
export function writeOpenclawPlugin(
  dir: string,
  emcliPath: string,
  version: string,
): { files: string[]; dir: string } {
  fs.mkdirSync(dir, { recursive: true });
  const files: string[] = [];
  for (const [name, content] of Object.entries(openclawPluginFiles(emcliPath, version))) {
    const p = path.join(dir, name);
    const tmp = `${p}.tmp-${process.pid}-${Date.now()}`;
    fs.writeFileSync(tmp, content);
    fs.renameSync(tmp, p);
    files.push(p);
  }
  return { files, dir };
}

/** spawn openclaw CLI(收 stdout+stderr,超时杀)。openclaw 不在 PATH → code:-1。 */
export function runOpenclaw(args: string[], timeoutMs = 30000): Promise<{ code: number; out: string }> {
  return new Promise((resolve) => {
    let child: ReturnType<typeof spawn>;
    try {
      child = spawn('openclaw', args, { stdio: ['ignore', 'pipe', 'pipe'] });
    } catch {
      resolve({ code: -1, out: 'spawn 失败' });
      return;
    }
    let out = '';
    let settled = false;
    const finish = (code: number): void => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      resolve({ code, out: out.trim() });
    };
    const timer = setTimeout(() => {
      try {
        child.kill();
      } catch {
        /* ignore */
      }
      finish(-2);
    }, timeoutMs);
    child.stdout?.on('data', (d: Buffer) => {
      out += d.toString();
    });
    child.stderr?.on('data', (d: Buffer) => {
      out += d.toString();
    });
    child.on('error', () => finish(-1));
    child.on('close', (code) => finish(code ?? -3));
  });
}

/** 经官方 CLI 配置 stdio MCP: 先 unset(幂等清旧条目)再 add(自带 probe 实连验证)。 */
export async function configureOpenclawMcp(
  emcliPath: string,
): Promise<{ ok: boolean; detail: string }> {
  await runOpenclaw(['mcp', 'unset', 'exomind'], 10000); // 幂等:不存在也不影响后续
  const r = await runOpenclaw(
    ['mcp', 'add', 'exomind', '--command', emcliPath, '--arg', 'mcp'],
    45000,
  );
  if (r.code !== 0) {
    return {
      ok: false,
      detail: `${r.out || `openclaw mcp add 退出码 ${r.code}`}(可手动: openclaw mcp add exomind --command ${emcliPath} --arg mcp)`,
    };
  }
  await runOpenclaw(['mcp', 'reload'], 15000); // 让运行中的 gateway 下一轮就用新配置
  return { ok: true, detail: r.out };
}

/** 开放 conversation-access hook 权限: 非内置插件挂 before_prompt_build 必须在
 *  openclaw.json 的 plugins.entries.exomind.hooks.allowConversationAccess=true,
 *  否则运行时被静默 block(inspect --runtime 会给 WARN)。保留该 entry 已有配置。 */
export function configureOpenclawHookAccess(
  openclawHome: string,
  backupFn?: (f: string) => void,
): { ok: boolean; file: string; reason?: string } {
  const file = path.join(openclawHome, 'openclaw.json');
  let d: Record<string, any> = {};
  try {
    d = JSON.parse(fs.readFileSync(file, 'utf-8'));
    if (!d || typeof d !== 'object') d = {};
  } catch (e) {
    if ((e as NodeJS.ErrnoException).code !== 'ENOENT') {
      return { ok: false, file, reason: `openclaw.json 读取失败(${e instanceof Error ? e.message : e}),未改动` };
    }
  }
  d.plugins ??= {};
  d.plugins.entries ??= {};
  const cur = (d.plugins.entries.exomind ?? {}) as Record<string, any>;
  if (cur?.hooks?.allowConversationAccess === true) {
    return { ok: true, file }; // 幂等
  }
  d.plugins.entries.exomind = { ...cur, hooks: { ...(cur.hooks ?? {}), allowConversationAccess: true } };
  backupFn?.(file);
  try {
    fs.mkdirSync(openclawHome, { recursive: true });
    const tmp = `${file}.tmp-${process.pid}-${Date.now()}`;
    fs.writeFileSync(tmp, JSON.stringify(d, null, 2) + '\n');
    fs.renameSync(tmp, file);
  } catch (e) {
    return { ok: false, file, reason: `openclaw.json 写入失败(${e instanceof Error ? e.message : e})` };
  }
  return { ok: true, file };
}

/** 安装 hook 桥接插件: 写包 + 开 hook 权限 + plugins install --link + reload。 */
export async function installOpenclawHookPlugin(
  pluginDir: string,
  emcliPath: string,
  version: string,
  openclawHome: string,
  backupFn?: (f: string) => void,
): Promise<{ ok: boolean; detail: string; dir: string }> {
  const { dir } = writeOpenclawPlugin(pluginDir, emcliPath, version);
  const access = configureOpenclawHookAccess(openclawHome, backupFn);
  if (!access.ok) {
    return { ok: false, dir, detail: access.reason ?? 'hook 权限配置失败' };
  }
  const r = await runOpenclaw(['plugins', 'install', '--link', dir, '--force'], 60000);
  if (r.code !== 0) {
    return {
      ok: false,
      dir,
      detail: `${r.out || `openclaw plugins install 退出码 ${r.code}`} — 可手动: openclaw plugins install --link ${dir} --force && openclaw gateway restart`,
    };
  }
  await runOpenclaw(['plugins', 'reload', 'exomind'], 30000); // 让运行中的 gateway 立即生效
  return { ok: true, dir, detail: r.out };
}
